version: 2.1

orbs:
  newhighsco: newhighsco/orb@1.7.0

only-version-tags: &only-version-tags
  filters:
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/

jobs:
  build:
    steps:
      - newhighsco/build:
          command: yarn build:storybook
          path-to-persist: build

workflows:
  version: 2
  test_and_release:
    jobs:
      - newhighsco/setup:
          name: setup
      - newhighsco/test:
          name: test
          requires:
            - setup
      - build:
          requires:
            - test
      - newhighsco/snapshot:
          name: snapshot
          requires:
            - build
      - newhighsco/release:
          name: release
          requires:
            - snapshot
          filters:
            branches:
              only:
                - main
  snapshot_version:
    jobs:
      - setup: *only-version-tags
      - build:
          <<: *only-version-tags
          requires:
            - setup
      - newhighsco/snapshot:
          <<: *only-version-tags
          name: snapshot
          requires:
            - build
